### PR TITLE
pull request take two..

### PR DESCRIPTION
**Pull request by david-mclean**
I think I have made most of the changes as you requested.

Take a look when you get five and let me know.

David

### CODE REVIEW

**Comment by ghost** [comment]
Thanks David, I'll try and find some time today.

**Comment by mikehadlow** [comment]
Hi David, I tried to merge your pull request today, but it doesn't seem like it's up to date? Sorry to ask you to do more, but could you merge it with my latest master? Thanks.

**Comment by david-mclean** [comment]
I did merge before i did the pull request. I guess if you have made changes
since then it might not have liked it.

I will take a look next week.

Cheers
On May 13, 2012 9:27 AM, "Mike Hadlow" <
reply@reply.github.com>
wrote:

**Comment by ghost** [comment]
Thanks David. Sorry for you to have to revisit it again.

**Comment by david-mclean** [comment]
No worries.

I have been looking at performance too so expect another pull with a couple
of small improvments maybe next week.

Cheers
On May 14, 2012 9:18 AM, "Mike Hadlow" <
reply@reply.github.com>
wrote:

**Comment by david-mclean** [comment]
Fingers crossed that'll fix the issue.

If not just shout.

Cheers

**Comment by ghost** [comment]
Thanks David, I might not have time until this weekend to look at it.

-----Original Message-----

**Comment by david-mclean** [comment]
Thats cool.

Thanks for your help with this.
On May 15, 2012 9:10 AM, "Mike Hadlow" <
reply@reply.github.com>
wrote:

**Pull request merged**
